### ISSUE TITLE
Negative integers not supported

### ISSUE THREAD

**Issue by shauns** [gavinwahl/postgres-json-schema#1]
Negative integers are not validated correctly:

```
select validate_json_schema('{"type": "integer"}', '-103948');
 validate_json_schema
----------------------
 f
(1 row)
```

I think the answer is to look at the type check where `data` is coerced to `text` and compared to a regex -- I'm not sure what's most performant, but maybe there's a built-in function to fulfill this check.

**Comment by gavinwahl** [comment]
Thanks!
