### ISSUE TITLE
Fix relocatability

### ISSUE THREAD

**Issue by daurnimator** [gavinwahl/postgres-json-schema#7]
Currently if you try and load postgres-json-schema into a non-default schema, it fails to find it's function `_validate_json_schema_type`.

```
psql:fixtures.psql:37: ERROR:  function _validate_json_schema_type(text, jsonb) does not exist
LINE 1: SELECT (SELECT NOT bool_or(_validate_json_schema_type(type, ...
                                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT (SELECT NOT bool_or(_validate_json_schema_type(type, data)) FROM unnest(types) type)
CONTEXT:  PL/pgSQL function validate_json_schema(jsonb,jsonb,jsonb) line 20 at IF
```

You should qualify your intra-module calls with `@extschema@.` (see https://www.postgresql.org/docs/current/extend-extensions.html)

**Comment by gavinwahl** [comment]
It seems like @extschema@ only works with relocatable=false, is that what you meant? I don't see any reason that it shouldn't be relocatable though.
